### ISSUE TITLE
NotImplementedError with add_signal_handler on Windows Platform

### ISSUE THREAD

**Issue by Ethycs** [comath/remote_llm#2]
On a Windows setup, I've encountered a NotImplementedError in the asyncio.events.add_signal_handler method. Here's the traceback:

```
Traceback (most recent call last):
  File "F:\OneDrive\jupyter\remote_llm\mock_llm.py", line 30, in <module>
    asyncio.run(main())
  File "C:\miniconda3\envs\remote_llm\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\miniconda3\envs\remote_llm\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "F:\OneDrive\jupyter\remote_llm\mock_llm.py", line 25, in main
    with graceful_exit([server]):
  File "C:\miniconda3\envs\remote_llm\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\miniconda3\envs\remote_llm\lib\site-packages\grpclib\utils.py", line 218, in graceful_exit
    loop.add_signal_handler(sig_num, _exit_handler, sig_num, servers, flag)
  File "C:\miniconda3\envs\remote_llm\lib\asyncio\events.py", line 553, in add_signal_handler
    raise NotImplementedError
NotImplementedError

```
It seems the add_signal_handler method is not supported on Windows platforms, leading to this error.

Windows 11 x64
Python 3.10

**Comment by erwinkramer** [comment]
related: https://github.com/python/cpython/issues/137863
